// Balance sheet
// Modify values here, save the file, then refresh the page to test changes.
window.GAME_BALANCE = {
  playerTable: {
    maxHp: 200,
    speed: 220,
    critChance: 0.05,
    critDamage: 1.5,
    pickupRange: 70,
    regen: 0.35,
    invuln: 0.38,
    xpCurve: [20, 26, 34, 42, 52, 64, 78, 94, 112, 132, 154, 178],
  },

  progression: {
    duration: 600,
    firstPathCap: 100,
    secondPathCap: 100,
  },

  pathCombat: {
    cap: 100,
    thresholds: {
      tier1: 30,
      tier2: 60,
      full: 100,
    },
    gain: {
      whiteUntouchedDelay: 4,
      whiteUntouchedInterval: 6,
      whiteUntouchedValue: 3,
      whiteEliteHighHpValue: 8,
      blackLowHpKillThreshold: 0.45,
      blackLowHpKillValue: 2,
      blackLowHpKillCooldown: 1.2,
      blackEliteMeleeValue: 8,
      meleeRange: 90,
      activeThreatRange: 120,
    },
    white: {
      tier1Duration: 6,
      tier1PickupBonus: 90,
      tier1AttractRadius: 220,
      tier1AttractSpeed: 260,
      tier1HealPct: 0.012,
      tier1HealCooldown: 0.25,
      tier2Duration: 8,
      tier2BarrierPct: 0.18,
      tier2BarrierMin: 40,
      tier2BarrierMax: 160,
      tier2EliteAttractMult: 2.2,
      tier2RefundThreshold: 0.7,
      tier2RefundValue: 8,
      fullPulseRadius: 110,
      fullBarrierPct: 0.12,
      fullBarrierMin: 30,
      fullBarrierMax: 120,
      fullDuration: 10,
      fullIncomingMult: 0.88,
      fullPickupBonus: 120,
      fullAttractRadius: 320,
      fullAttractSpeed: 520,
      fullHealPct: 0.015,
      fullHealCooldown: 0.25,
    },
    black: {
      tier1Duration: 6,
      tier1DamageMult: 1.14,
      tier1CastMult: 1.12,
      tier1MoveMult: 1.12,
      tier1BurstRadius: 44,
      tier1BurstBase: 18,
      tier1BurstEnemyMaxHpPct: 0.12,
      tier1Drain: 0.006,
      tier2Duration: 8,
      tier2IncomingMult: 1.1,
      tier2ActiveCooldownRate: 1.35,
      tier2AssaultStackMult: 0.04,
      tier2AssaultMaxStacks: 5,
      tier2AssaultDuration: 2,
      tier2AssaultCooldown: 0.25,
      tier2NormalExecuteThreshold: 0.22,
      tier2NormalExecuteMult: 1.6,
      tier2EliteExecuteThreshold: 0.14,
      tier2EliteExecuteMult: 1.35,
      tier2BossExecuteThreshold: 0.08,
      tier2BossExecuteMult: 1.18,
      fullPulseRadius: 120,
      fullPulseBase: 90,
      fullDuration: 10,
      fullDamageMult: 1.22,
      fullCritChanceBonus: 0.15,
      fullActiveCooldownRate: 1.2,
      fullBurstRadiusMult: 1.35,
      fullDrain: 0.01,
    },
  },

  activeSkillTable: {
    sword: { baseCooldown: 12 },
    thunder: { baseCooldown: 14 },
    flame: { baseCooldown: 13 },
    guard: { baseCooldown: 10 },
  },

  reincarnationTable: {
    storageKey: "wannabe-immortal-save",
    pointsFromTimeDivisor: 60,
    pointsFromKillsDivisor: 20,
    transformBonus: 4,
    bossWinBonus: 10,
    pathWinBonus: 6,
    upgrades: {
      hp1: { name: "命元残存", cost: 6, maxLevel: 3, effectPerLevel: 10 },
      xp1: { name: "聚灵残痕", cost: 6, maxLevel: 3, effectPerLevel: 0.08 },
      pickup1: { name: "摄气残痕", cost: 4, maxLevel: 2, effectPerLevel: 0.15 },
      white1: { name: "白炁余韵", cost: 5, maxLevel: 2, effectPerLevel: 0.1 },
      black1: { name: "黑炁余烬", cost: 5, maxLevel: 2, effectPerLevel: 0.1 },
      starter: { name: "前世所悟", cost: 8, maxLevel: 1, effectPerLevel: 1 },
    },
  },

  waves: {
    spawnIntervalEarly: 2.6,
    spawnIntervalMid: 2.1,
    spawnIntervalLate: 1.85,
    spawnIntervalEnd: 1.45,
    stageBandEarly: 18,
    stageBandMid: 38,
    stageBandLate: 58,
    levelIntervalReduction: 0.14,
    minSpawnInterval: 1.15,

    countEarly: 4,
    countMid: 5,
    countLate: 5,
    countEnd: 6,

    stageProfiles: {
      1: {
        intervalOffset: 0,
        countOffset: 0,
        gruntWeight: 6,
        chargerWeight: 2,
        rangedWeight: 2,
      },
      2: {
        intervalOffset: 0.05,
        countOffset: 1,
        gruntWeight: 5.7,
        chargerWeight: 2.1,
        rangedWeight: 2.2,
      },
      3: {
        intervalOffset: -0.12,
        countOffset: 1,
        gruntWeight: 4.9,
        chargerWeight: 2.8,
        rangedWeight: 2.6,
      },
    },

    eliteSchedule: [92, 205, 330, 455],

    healthBands: [
      { until: 120, mult: 1.1 },
      { until: 240, mult: 1.65 },
      { until: 360, mult: 2.2 },
      { until: 480, mult: 2.95 },
      { until: Infinity, mult: 3.5 },
    ],

    damageBands: [
      { until: 120, mult: 1.15 },
      { until: 240, mult: 1.35 },
      { until: 360, mult: 1.6 },
      { until: 480, mult: 1.9 },
      { until: Infinity, mult: 2.2 },
    ],
  },

  monsterTable: {
    grunt: {
      name: "小妖",
      hp: 42,
      damage: 10,
      speed: 82,
      radius: 13,
      xp: 3,
      orb: 2,
      meleeCooldown: 0.45,
    },

    charger: {
      name: "冲锋鬼",
      hp: 52,
      damage: 14,
      speed: 102,
      radius: 18,
      xp: 4,
      orb: 4,
      meleeCooldown: 0.6,
      dashCooldown: 1.35,
      dashSpeedMult: 2.35,
    },

    ranged: {
      name: "远程灵体",
      hp: 40,
      damage: 11,
      speed: 60,
      radius: 12,
      xp: 4,
      orb: 4,
      meleeCooldown: 0.55,
      shotCooldown: 1.3,
      projectileSpeed: 230,
      preferredRange: 190,
    },

    elite: {
      name: "精英护法",
      hp: 780,
      damage: 20,
      speed: 72,
      radius: 28,
      xp: 18,
      orb: 10,
      meleeCooldown: 0.76,
    },

    boss: {
      name: "天劫法相",
      xp: 46,
      orb: 20,
      hp: 4000,
      damage: 28,
      speed: 80,
      radius: 34,
      contactCooldown: 0.62,

      phaseTwoAt: 0.7,
      phaseThreeAt: 0.35,

      attackCooldowns: {
        phase1: 0.95,
        phase2: 0.72,
        phase3: 0.52,
      },

      radialProjectileCount: 12,
      radialProjectileSpeed: 240,

      fanProjectileCount: 5,
      fanProjectileSpeed: 300,

      waveRadius: 150,
      waveDamageMult: 0.9,

      summonCountPhase2: 2,
      summonCountPhase3: 3,
    },
  },

  bossRoundTable: {
    1: {
      id: "trial-window",
      name: "问机法傀",
      role: "主动技验收 Boss",
      hpMult: 0.88,
      damageMult: 0.88,
      speedMult: 0.92,
      radius: 36,
      contactCooldown: 0.66,
      contactDamageMult: 0.9,
      phaseThresholds: [0.64],
      phaseShiftPause: 0.9,
      phases: [
        {
          name: "试锋",
          desiredRange: 132,
          moveMult: 0.94,
          cooldown: 1.24,
          sequence: ["counterFan", "sweepLane", "focusBurst"],
        },
        {
          name: "开门",
          desiredRange: 118,
          moveMult: 1.02,
          cooldown: 1.02,
          sequence: ["counterFan", "focusBurst", "crossSweep", "counterFan"],
        },
      ],
      skills: {
        counterFan: {
          kind: "counter-fan",
          name: "试锋珠雨",
          category: "counterable",
          windup: 0.72,
          recovery: 0.32,
          opening: 0.88,
          projectileCount: 4,
          spread: 0.2,
          projectileSpeed: 238,
          projectileLife: 4,
          projectileRadius: 8,
          damageMult: 0.44,
        },
        sweepLane: {
          kind: "lane-sweep",
          name: "裁线",
          category: "uncounterable",
          windup: 0.82,
          recovery: 0.2,
          opening: 1.24,
          laneWidth: 84,
          laneLength: 620,
          laneCount: 2,
          angleSpread: 0.46,
          sequentialDelay: 0.2,
          damageMult: 0.66,
        },
        crossSweep: {
          kind: "lane-cross",
          name: "断章十字",
          category: "uncounterable",
          windup: 0.78,
          recovery: 0.16,
          opening: 1.02,
          laneWidth: 96,
          laneLength: 700,
          damageMult: 0.68,
        },
        focusBurst: {
          kind: "focus-burst",
          name: "驻印落罚",
          category: "uncounterable",
          windup: 0.88,
          recovery: 0.24,
          opening: 1.14,
          zoneCount: 3,
          radius: 54,
          spread: 88,
          sequentialDelay: 0.14,
          damageMult: 0.6,
        },
      },
    },
    2: {
      id: "route-pressure",
      name: "镇路监军",
      role: "单一路线毕业 Boss",
      hpMult: 1.12,
      damageMult: 1.04,
      speedMult: 1.02,
      radius: 38,
      contactCooldown: 0.56,
      contactDamageMult: 1,
      phaseThresholds: [0.58],
      phaseShiftPause: 0.72,
      phases: [
        {
          name: "压阵",
          desiredRange: 174,
          moveMult: 1,
          cooldown: 1.02,
          sequence: ["escortCall", "commandBolts", "pathCollapse"],
        },
        {
          name: "围剿",
          desiredRange: 188,
          moveMult: 1.08,
          cooldown: 0.84,
          sequence: ["sealZones", "escortCall", "commandBolts", "pathCollapse"],
        },
      ],
      skills: {
        escortCall: {
          kind: "escort-call",
          name: "伴生压阵",
          category: "uncounterable",
          windup: 0.68,
          recovery: 0.22,
          opening: 0.42,
          summonPairs: 2,
          damageMult: 0.3,
          pulseRadius: 84,
        },
        commandBolts: {
          kind: "counter-fan",
          name: "督军号令",
          category: "counterable",
          windup: 0.66,
          recovery: 0.24,
          opening: 0.56,
          projectileCount: 3,
          spread: 0.16,
          projectileSpeed: 300,
          projectileLife: 4.2,
          projectileRadius: 9,
          damageMult: 0.5,
        },
        pathCollapse: {
          kind: "lane-sweep",
          name: "封路判行",
          category: "uncounterable",
          windup: 0.8,
          recovery: 0.18,
          opening: 0.7,
          laneWidth: 98,
          laneLength: 720,
          laneCount: 3,
          angleSpread: 0.34,
          sequentialDelay: 0.16,
          damageMult: 0.76,
        },
        sealZones: {
          kind: "seal-zones",
          name: "锁域符",
          category: "uncounterable",
          windup: 0.76,
          recovery: 0.2,
          opening: 0.38,
          zoneCount: 3,
          radius: 62,
          spread: 132,
          sequentialDelay: 0.1,
          damageMult: 0.34,
          hazardDuration: 3.8,
          hazardTick: 0.55,
          hazardDamageMult: 0.22,
        },
      },
    },
    3: {
      id: "endgame-truth",
      name: "终劫真相",
      role: "终局验收 Boss",
      hpMult: 1.34,
      damageMult: 1.18,
      speedMult: 1.08,
      radius: 40,
      contactCooldown: 0.48,
      contactDamageMult: 1.08,
      phaseThresholds: [0.72, 0.36],
      phaseShiftPause: 0.76,
      phases: [
        {
          name: "压顶",
          desiredRange: 152,
          moveMult: 1.02,
          cooldown: 0.94,
          sequence: ["meteorField", "heavenLance", "ringCollapse"],
        },
        {
          name: "断流",
          desiredRange: 164,
          moveMult: 1.12,
          cooldown: 0.74,
          sequence: ["judgementCross", "meteorField", "heavenLance", "ringCollapse"],
        },
        {
          name: "极证",
          desiredRange: 170,
          moveMult: 1.22,
          cooldown: 0.58,
          sequence: ["meteorField", "heavenLance", "judgementCross", "ringCollapse", "heavenLance"],
        },
      ],
      skills: {
        heavenLance: {
          kind: "counter-fan",
          name: "天锋判矛",
          category: "counterable",
          windup: 0.62,
          recovery: 0.18,
          opening: 0.54,
          projectileCount: 5,
          spread: 0.12,
          projectileSpeed: 332,
          projectileLife: 4.4,
          projectileRadius: 10,
          damageMult: 0.54,
        },
        meteorField: {
          kind: "focus-burst",
          name: "坠星劫火",
          category: "uncounterable",
          windup: 0.74,
          recovery: 0.16,
          opening: 0.34,
          zoneCount: 5,
          radius: 56,
          spread: 126,
          sequentialDelay: 0.1,
          damageMult: 0.42,
        },
        judgementCross: {
          kind: "lane-cross",
          name: "审判十字",
          category: "uncounterable",
          windup: 0.68,
          recovery: 0.16,
          opening: 0.64,
          laneWidth: 108,
          laneLength: 760,
          damageMult: 0.82,
        },
        ringCollapse: {
          kind: "ring-collapse",
          name: "内外两断",
          category: "uncounterable",
          windup: 0.78,
          recovery: 0.18,
          opening: 0.96,
          innerRadius: 112,
          outerRadius: 236,
          damageMult: 0.82,
        },
      },
    },
  },
};
